apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    # 주문하기을 버튼을 누르면 이동하는 url
    path("logs/", views.OrderList.as_view(), name="order_list"),
    path("logs/<int:pk>/", views.OrderLogDetail.as_view(), name="order_detail"),
    path("create/", views.order_create, name="order_create"),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("products/", views.ProductList.as_view(), name="product_list"),
    path("products/<int:pk>/", views.product_detail, name="product_detail"),
    path("products/category/", views.product_category, name="product_category"),
]

apps/sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'
urlpatterns = [
    path('', views.sales_list, name='sales_list'),
    path('register/', views.register_product, name='register_product'),
    path('edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.products import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("orders/", include("apps.orders.urls")),
    path("carts/", include("apps.carts.urls")),
    path('sales/', include("apps.sales.urls")),
    path("admin/", admin.site.urls),
]

apps/products/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# 카테고리 모델
class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


# 상품 모델
class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='products/')
    price = models.IntegerField()
    stock_quantity = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.pk:  # 상품이 이미 데이터베이스에 존재하는 경우 (즉, 이것이 '업데이트' 작업임)
            orig = Product.objects.get(pk=self.pk)
            if (orig.name != self.name or orig.price != self.price):  # 이름이나 가격에 변화가 있는 경우
                self.create_snapshot()
            if orig.image != self.image:  # 이미지 변경 후 이전 이미지 삭제
                orig.image.delete(save=False)
        super().save(*args, **kwargs)
    
    def create_snapshot(self):
        ProductSnapshot.objects.create(
            product=self,
            seller=self.seller,
            name=self.name,
            description=self.description,
            price=self.price,
            stock_quantity=self.stock_quantity,
            category=self.category
        )

# 상품 스냅샷 모델 (판매자가 상품 수정을 할 경우 구매내역의 상품 정보(가격)은 바뀌면 안되기 때문)
class ProductSnapshot(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.IntegerField()
    stock_quantity = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    snapshot_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-snapshot_date']
    
    def __str__(self):
        return f"Snapshot of {self.name} on {self.snapshot_date.strftime('%Y-%m-%d')}"

apps/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'price', 'stock_quantity', 'category']

apps/products/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Product, Category
from apps.carts.models import Cart, CartDetail
from apps.carts.forms import AddToCartForm
from apps.orders.models import Order
from django.http import JsonResponse
import json
from django.core.serializers import serialize

class ProductList(ListView):
    model = Product
    template_name = "products/product_list.html"
    paginate_by = 12
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["orders"] = Order.objects.filter(user=self.request.user)
            context['products'] = Product.objects.filter(seller=self.request.user)
            cart, _ = Cart.objects.get_or_create(user=self.request.user)
            context['cart'] = cart
            context['categories'] = Category.objects.all()
        else:
            context["orders"] = None
            context['products'] = None
            context['cart'] = None
            context['categories'] = Category.objects.all()
        return context


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        # 사용자가 로그인이 되어있을 경우에만 아래의 코드 실행
        if request.user.is_authenticated:
            # 폼에서 상품의 재고 수 이상을 입력 받으면 유효성 검사를 통과하지 못하게 초기값 설정
            form = AddToCartForm(request.POST, max_value=product.stock_quantity)

            # 장바구니에 담기 버튼을 눌렀을 경우
            if "add_to_cart" in request.POST:
                if form.is_valid():
                    quantity = int(form.cleaned_data.get("quantity"))
                    if quantity <= product.stock_quantity:
                        # 카트 생성 혹은 이미 있을경우 가져오기
                        cart, created = Cart.objects.get_or_create(user=request.user)
                        cart_detail, created = CartDetail.objects.get_or_create(
                            cart=cart, product=product
                        )

                        if not created:
                            cart_detail.quantity += quantity
                        else:
                            cart_detail.quantity = quantity
                        cart_detail.save()
                        return redirect("carts:cart")
                else:
                    context = {"object": product, "form": form}
                    return render(request, "products/product_detail.html", context)

            # 바로 주문하기 버튼을 눌렀을 경우
            if "order_now" in request.POST:
                if form.is_valid():
                    quantity = int(form.cleaned_data.get("quantity"))
                    if quantity <= product.stock_quantity:
                        cart, created = Cart.objects.get_or_create(user=request.user)
                        cart_detail, created = CartDetail.objects.get_or_create(
                            cart=cart, product=product
                        )

                        if not created:
                            cart_detail.quantity += quantity
                        else:
                            cart_detail.quantity = quantity
                            
                        product.stock_quantity -= quantity
                        product.save()

                        cart_detail.save()
                    return redirect("orders:order_create")
                # 유효성 검사를 통과하지 못했을 경우 에러메시지를 form에 넣어줌
                else:
                    context = {"object": product, "form": form}
                    return render(request, "products/product_detail.html", context)
        # 사용자가 로그인이 되어있지 않을 경우 로그인 페이지로 이동
        else:
            return redirect("accounts:login")
    # GET으로 넘어왔을 경우 Form 생성
    else:
        form = AddToCartForm(max_value=product.stock_quantity)

    context = {"object": product, "form": form}

    return render(request, "products/product_detail.html", context)

def product_category(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        category_id = data['categoryId']
        if data['mode'] == 0:
            products = Product.objects.filter(seller=request.user, category_id=category_id)
        else:
            products = Product.objects.filter(category_id=category_id)
        context = {
            'category_products': serialize('json', products)
        }
        return JsonResponse(context)

templates/products/product_detail.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <!-- 이미지 -->
            <img src="{{ object.image.url }}" alt="{{ object.name }}" class="img-fluid rounded">
        </div>
        <div class="col-md-6">
            <!-- 상품 정보 -->
            <h2>{{ object.name }}</h2>
            <p class="text-muted">{{ object.category.name }}</p>
            <p>{{ object.description }}</p>
            <h3>{{ object.price|intcomma }}원</h3>
            <p>남은 수량: {{ object.stock_quantity }}</p>
            <hr>
            <!-- 구매 옵션 폼 -->
            <form method="post" class="form-inline">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <input type="number" name="quantity" value="1" min="1" class="form-control d-inline-block" style="width: 100px;">
                    <button type="submit" name="add_to_cart" class="btn btn-outline-primary  mx-2">장바구니 담기</button>
                    <button type="submit" name="order_now" class="btn btn-outline-success ">바로 주문하기</button>
                </div>
                
            </form>
            <!-- 폼 에러 메시지 -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block extra-links %}
<div class="container mt-3">
    <a href="{% url 'home' %}" class="btn btn-outline-secondary">홈으로</a>
</div>
{% endblock extra-links %}

templates/products/product_list_copy.html
{% extends 'base.html' %}


{% block content %}


{% if user.is_active %}
<h1>판매자일 경우 아래에 상품 등록하러 갈 수 있는 링크가 보임</h1>
{% if user.is_seller %}
<a href="{% url 'sales:register_product' %}">상품 등록하기</a>
<hr>
<h1>등록한 상품</h1>
{% for product in products %}
<a href="{% url 'sales:edit_product' product.id %}">{{product}} 상품 수정하러가기</a>
{% endfor %}
{% endif %}
<hr>
<h1>결제한 내역이 있으면 아래에 주문내역 보기 버튼이 나옴</h1>
{% if orders %}
<a href="{% url 'orders:order_list' %}">주문내역 보기</a>
{% endif %}
{% else %}
{% endif %}
<hr>


<h1>상품 리스트</h1>
<br>
{% for object in object_list %}
<a href="{% url 'products:product_detail' object.id %}">{{ object.name }}</a>
<hr>
{% endfor %}




{% endblock content %}


{% block extra-script %}
{% if messages %}
{% for message in messages %}
<script>
    alert("{{ message }}");
</script>
{% endfor %}
{% endif %}
{% endblock extra-script %}