apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("edit/", views.EditView.as_view(), name="edit"),
    path(
        "password_change/",
        views.CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("delete/", views.delete_account, name="delete_account"),
]

apps/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('update/', views.update_cart, name='update_cart'),
]

apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    # 주문하기을 버튼을 누르면 이동하는 url
    path("logs/", views.OrderList.as_view(), name="order_list"),
    path("logs/<int:pk>/", views.OrderLogDetail.as_view(), name="order_detail"),
    path("create/", views.order_create, name="order_create"),
]

apps/sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'
urlpatterns = [
    path('', views.sales_list, name='sales_list'),
    path('register/', views.register_product, name='register_product'),
    path('edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.products import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("orders/", include("apps.orders.urls")),
    path("carts/", include("apps.carts.urls")),
    path('sales/', include("apps.sales.urls")),
    path("admin/", admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load widget_tweaks %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} MiniEbay {% endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vZJx9n8xUm8rPwhHhaUpPegi5h9R7DEpZJqzFmq8H7lMdC-4iQ6g9Rrtpp7lvR7F" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
            height: 100%;

        }

        .wrapper {
            display: flex;
            flex-direction: column;
            height: 100%;
        }

        .main-content {
            flex: 1;
        }

        .content-padding {
            padding: 0 100px 0 100px;
        }

        footer {
            padding: 20px 0;
            background: #f6f6f6;
        }

        .login-signup-btn {
            padding-left: 15px;
            /* 왼쪽 패딩 추가 */
            padding-right: 15px;
            /* 오른쪽 패딩 추가 */
            white-space: nowrap;
            /* 텍스트 줄바꿈 방지 */
        }
    </style>
    {% block extra-style %} {% endblock extra-style %}
</head>

<body>
    <div class="wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'miniebay.png' %}" alt="logo" width="150"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">홈</a>
                        {% block category-link %}
                        {% endblock category-link %}                        
                        {% if user.is_active %}
                            {% if not user.is_seller %}
                            <a class="nav-link" href="{% url 'carts:cart' %}">장바구니</a>
                            {% endif %}
                            {% if user.is_seller %}
                            <a class="nav-link" href="{% url 'sales:register_product' %}">상품 등록</a>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% if user.is_active %}
                    <div class="navbar-nav ms-auto">
                        <a class="nav-link px-0" href="{% url 'accounts:edit' %}">{{user}}</a>
                        <span class="nav-link">|</span>
                        {% if user.is_seller %}
                            <a class="nav-link px-0 " href="{% url 'sales:sales_list' %}">판매 내역</a>
                        {% else %}
                            <a class="nav-link px-0 " href="{% url 'orders:order_list' %}">주문 내역</a>
                        {% endif %}
                        <span class="nav-link">|</span>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="nav-link px-0 " type="submit">로그아웃</button>
                        </form>
                    </div>
                    {% else %}
                    <div class="navbar-nav ms-auto">
                        <a class="nav-link px-0 " href="{% url 'accounts:login' %}">로그인</a>
                        <span class="nav-link">|</span>
                        <a class="nav-link px-0" href="{% url 'accounts:signup' %}">회원가입</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>


        <div class="main-content">
            <div class="container mt-5 content-padding">
                {% block content %}{% endblock content %}
            </div>
            
        </div>

        <footer class="mt-5">
            <div class="d-flex justify-content-center ">
                <span class="text-center text-secondary mx-2">&copy; 2024 Copyright</span>
                <a class="text-decoration-none fw-semibold text-secondary  " href="https://github.com/madEffort/django-mini-ebay.git">madEffort</a>
            </div>
            {% block footer %} {% endblock footer%}
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    {% block extra-script %} {% endblock extra-script %}
</body>

</html>