apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    # 주문하기을 버튼을 누르면 이동하는 url
    path("logs/", views.OrderList.as_view(), name="order_list"),
    path("logs/<int:pk>/", views.OrderLogDetail.as_view(), name="order_detail"),
    path("create/", views.order_create, name="order_create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.products import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.ProductList.as_view(), name="home"),
    path("accounts/", include("apps.accounts.urls")),
    path("products/", include("apps.products.urls")),
    path("orders/", include("apps.orders.urls")),
    path("carts/", include("apps.carts.urls")),
    path('sales/', include("apps.sales.urls")),
    path("admin/", admin.site.urls),
]

apps/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from apps.products.models import Product, ProductSnapshot

User = get_user_model()


# 주문 모델
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    total_amount = models.IntegerField()
    STATUS_CHOICES = [
        ("processing", "Processing"),
        ("shipped", "Shipped"),
        ("delivered", "Delivered"),
    ]
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="processing"
    )
    
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"


# 주문 상세 모델
class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_snapshot = models.ForeignKey(ProductSnapshot, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    
    class Meta:
        ordering = ['-id']
    
    def __str__(self):
        return f"Detail for Order {self.order.id}"

apps/orders/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from apps.carts.models import Cart
from apps.products.models import ProductSnapshot
from .models import Order, OrderDetail
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def order_create(request):
    user = request.user
    cart = Cart.objects.get(user=user)

    # 역참조를 통해 카트에 담긴 것들을 가져옴
    cart_items = cart.cartdetail_set.all()

    # 총 얼마인지 카트에 담긴 상품을 반복문 돌려 가격의 총합을 구함
    total_amount = sum(item.product.price * item.quantity for item in cart_items)

    if request.method == "POST":

        # 주문하기 버튼을 누르면 새로운 주문을 생성
        order = Order.objects.create(
            user=user,
            total_amount=total_amount,
        )
        
        # 주문에 카트에 담긴 상품들 추가 하여 db에 저장
        for item in cart_items:
            
            # snapshot, created = ProductSnapshot.objects.get_or_create(
            #     product=item.product,
            #     seller=item.product.seller,
            #     name=item.product.name,
            #     description=item.product.description,
            #     price=item.product.price,
            #     stock_quantity=item.product.stock_quantity,
            #     category=item.product.category,
            #     defaults={'product': item.product}
            # )
            latest_snapshot = ProductSnapshot.objects.filter(product=item.product).first()
            
            if not latest_snapshot:
                snapshot = ProductSnapshot.objects.create(
                product=item.product,
                seller=item.product.seller,
                name=item.product.name,
                description=item.product.description,
                price=item.product.price,
                stock_quantity=item.product.stock_quantity,
                category=item.product.category,
            )
                
            else: 
                snapshot = latest_snapshot
            
            OrderDetail.objects.create(
                order=order,
                product_snapshot=snapshot,
                quantity=item.quantity,
                price=snapshot.price,
            )
            
            item.product.stock_quantity -= item.quantity
            item.product.save()
            

        # DB에 저장한 후에는 카트 비우기
        cart_items.delete()

        messages.success(request, "결제가 완료되었습니다.")
        return redirect("home")

    context = {"cart_items": cart_items, "total_amount": total_amount}

    return render(request, "orders/order.html", context)


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    template_name = "orders/order_list.html"

    # 본인의 주문내역만 가져오게 쿼리셋 수정
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderLogDetail(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/order_detail.html"

templates/orders/order.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load humanize %}

{% block content %}
<div class="container mt-5">
    <h2>주문</h2>
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">상품 이미지</th>
                    <th scope="col">상품명</th>
                    <th scope="col">카테고리</th>
                    <th scope="col">가격</th>
                    <th scope="col">설명</th>
                    <th scope="col">수량</th>
                    <th scope="col">합계</th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td><img src="{{ cart_item.product.image.url }}" alt="{{ cart_item.product.name }}" class="img-fluid" width="80"></td>
                    <td>{{ cart_item.product.name }}</td>
                    <td>{{ cart_item.product.category.name }}</td>
                    <td>{{ cart_item.product.price|intcomma }}원</td>
                    <td>{{ cart_item.product.description }}</td>
                    <td>{{ cart_item.quantity }}개</td>
                    <td>{{ cart_item.product.price|multiply:cart_item.quantity|intcomma }}원</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-end ">
        <h3 class="text-right">총 금액: {{ total_amount|intcomma }}원</h3>
    </div>

    <div class="d-flex justify-content-end ">
        {% if total_amount != 0 %}
        <form method="post" class="text-right">
            {% csrf_token %}
            <button type="button" id="payButton" class="btn btn-outline-primary ">결제하기</button>
            <div id="paymentValidation" style="display: none; margin-top: 10px;">
                <input class="" type="text" id="validationInput" placeholder="'결제'라고 입력하세요.">
                <button type="submit" class="btn btn-outline-success ">결제</button>
            </div>
        </form>
        {% endif %}
    </div>

</div>
{% endblock content %}

{% block extra-script %}
<script>
    document.getElementById('payButton').addEventListener('click', function() {
        document.getElementById('paymentValidation').style.display = 'block';
        this.style.display = 'none'; // Hide the '결제하기' button after it's clicked
    });
    
    document.getElementById('paymentForm').onsubmit = function() {
        var validationInput = document.getElementById('validationInput').value;
        if (validationInput === '결제') {
            return true; // Allow form submission
        } else {
            alert('올바른 키워드를 입력해 주세요: "결제"');
            return false; // Prevent form submission
        }
    };
    </script>
{% endblock extra-script %}

templates/orders/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load humanize %}

{% block content %}
<div class="container mt-5">
    <h2>주문 내역</h2>
    <hr>
    {% if object.orderdetail_set.all %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">상품 이미지</th>
                <th scope="col">상품명</th>
                <th scope="col">설명</th>
                <th scope="col">단가</th>
                <th scope="col">수량</th>
                <th scope="col">합계</th>
                <th scope="col">상태</th>
            </tr>
        </thead>
        <tbody>
            {% for detail in object.orderdetail_set.all %}
            <tr>
                <td><img src="{{ detail.product_snapshot.product.image.url }}" alt="{{ detail.product_snapshot.product.name }}" class="img-fluid" width="100"></td>
                <td>{{ detail.product_snapshot.name }}</td>
                <td>{{ detail.product_snapshot.description }}</td>
                <td>{{ detail.price|intcomma }}원</td>
                <td>{{ detail.quantity }}</td>
                <td>{{ detail.price|multiply:detail.quantity|intcomma }}원</td>
                <td>{{ detail.order.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-end ">
        <h3 class="text-right">총 금액: {{ object.total_amount|intcomma }}원</h3>
    </div>
    
    {% else %}
    <div class="alert alert-info" role="alert">
        이 주문에 대한 상세 내역이 없습니다.
    </div>
    {% endif %}
</div>
{% endblock content %}

templates/orders/order_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2>주문 내역</h2>
    <hr>
    {% if object_list %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">주문 날짜</th>
                <th scope="col">상세 정보</th>
            </tr>
        </thead>
        <tbody>
            {% for order in object_list %}
            <tr>
                <td>{{ order.order_date|date:"Y-m-d H:i" }}</td>
                <td><a href="{% url 'orders:order_detail' order.id %}" class="btn btn-outline-primary btn-sm">자세히 보기</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info" role="alert">
        주문 내역이 없습니다.
    </div>
    {% endif %}
</div>
{% endblock content %}